### ISSUE TITLE
topic: curl turns 25 years

### ISSUE THREAD

**Issue by bagder** [fossified/podcast#12]
Ok, sorry for being egocentric here but on March 20 2023, the @curl project turns 25 years old and it is kind of a big thing for me. :partying_face: 

![curl-8 0 0](https://user-images.githubusercontent.com/177011/224275706-3375b4f3-4937-4d66-aa63-7158f66a2abd.jpg)

**Comment by stdevel** [comment]
Would be great to hear some of your highlights and insights on this project!

**Comment by hesa** [comment]
Want to hear weird stories, e.g. the recent Microsoft curl package

**Comment by bch** [comment]
Technical tools and techniques for keeping the project on the rails. Editors, compilers, build system, tools like Val grind...

**Comment by bpoyner** [comment]
Any extraordinary use of curl that you know about, e.g. the mars helicopter.

**Comment by oej** [comment]
This is a very relevant topic.

**Comment by hesa** [comment]
Curl vs Postman
* pros
* cons

Curl vs Wget (I am sure none of the maintainers sees a rivalry)

**Comment by oej** [comment]
Depending on the "one-man" curl project in your mission critical software :-)

**Comment by bagder** [comment]
I think it could be good to address these commonly asked questions that are curl related but not strictly about it turning 25:

- is this a solo-project (we welcomed the 1125th commit author the other day)
- how do I (and curl) make money (I sell commercial support via wolfSSL)
- how is this a full-time job? (I work on curl 50-60 hours per week)

**Comment by bagder** [comment]
from [William Reardon](https://twitter.com/wdr1) on [twitter](https://twitter.com/wdr1/status/1635305806672588808):

How has the toolchain evolved over the years?

**Comment by andrew** [comment]
Are there any significant forks of curl that have ever gained any traction?

**Comment by rybak** [comment]
What kind of practices do you follow in the curl repository for better Git log? I know you don't use GitHub's merge for pull requests, because it doesn't fit your use-case. How much time do you spend reviewing structure of pull requests and commit messages?

**Comment by bagder** [comment]
From [Michael Mattsson](https://twitter.com/datamattsson) on [twitter](https://twitter.com/datamattsson/status/1635417431006117891):

What advice would you offer to a younger generation that aspire to maintain an open source project for 25 years as graciously and humble as you have?

**Comment by linusnielsen** [comment]
I remember when I got a call in the evening by a very angry lady who claimed that we (Haxx) had hacked her computer. Her son had found curl in a malware, along with the company name "Haxx". My phone number is listed as the contact number for Haxx, so guess who she called?

It took me several evenings of patient explanation over the phone to make her understand that we are not the ones who "hacked" her computer.

Similar things have actually happened quite a few times over the years. I guess the company name Haxx has its drawbacks, despite being such a cool name. :-)

**Comment by lhjnilsson** [comment]
Grattis!! 
Would it be possible to calculate the average number of curl- calls an average human does per day? Not through the terminal, but through various applications and their dependencies. 10, 100, 10 000?!

**Comment by bagder** [comment]
I did some math and rough guessing of curl traffic in that vein in a blog post in 2019: https://daniel.haxx.se/blog/2019/12/04/daily-web-traffic/

> This simple-minded estimate would imply that maybe, perhaps, possibly, curl transfers more data an average day than any single individual browser flavor does

**Comment by bagder** [comment]
This was episode 2: #44
