### ISSUE TITLE
ogg-only causes some issues

### ISSUE THREAD

**Issue by bagder** [fossified/podcast#19]
The pilot was shipped in ogg format only but reports are trickling in that this causes problems. So far I've heard:

- iOS Downcast seems to not like ogg
- I assume that's the reason why I can't play it in Pocket Casts

@e8johan has said he'll work on getting an mp3 version up as well.

**Comment by bagder** [comment]
@hesa just added it

**Comment by bagder** [comment]
I was told the podcast does not play on Safari (on the web I presume)  - so maybe we should rather play the mp3 there ?

**Comment by bagder** [comment]
According to https://caniuse.com/?search=ogg, Safari on IOS does not support ogg audio

**Comment by hesa** [comment]
Browsers are now getting mp3 instead of ogg

Can someone confirm it works?

**Comment by bagder** [comment]
:heavy_check_mark:  I've had it confirmed by someone
