### ISSUE TITLE
Feed issues, multiple enclosure elements

### ISSUE THREAD

**Issue by sreimers** [fossified/podcast#24]
Thanks for providing this podcast, I think most podcast apps have problems with multiple enclosure elements and only use the ogg element (e.g. Overcast on iOS, reports `invalid audio file` after download):

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpod.fossified.com%2Fpodcast.rss

The general approach is to provide separate feeds or mp3 only.

**Comment by kolaente** [comment]
I have the same problem with the newest episode but was able to play the pilot without issues.
