### ISSUE TITLE
Publish S01E01

### ISSUE THREAD

**Issue by hesa** [fossified/podcast#30]
- [x] (H) collect links
- [x] (J) merge and trim audio files
- [x] (J) add new podcast episode (use `content` for links etc from guests)

**Comment by bagder** [comment]
I figured we can also create a discussion thread for each new episode for discussions related to that particular one as the topics/issues will be closed when handled.

I made one for episode 0, the pilot here: https://github.com/fossified/podcast/discussions/17

**Comment by e8johan** [comment]
Done
