### ISSUE TITLE
Input needed: News March 2023

### ISSUE THREAD

**Issue by hesa** [fossified/podcast#31]
Suggest news (by commenting this issue) you think we should cover in our March episodes

**Comment by bagder** [comment]
[Docker is deleting Open Source organisations](https://blog.alexellis.io/docker-is-deleting-open-source-images/)

**Comment by StaffanMelin** [comment]
Inkscape - 20 year anniversary!

https://inkscape.org/news/2023/02/17/13-about-screen-contest-celebrating-20-years-of-in/

**Comment by hesa** [comment]
Kali Linux 10 years old

**Comment by hesa** [comment]
https://www.qubes-os.org/news/2023/03/14/qubes-4-1-2/

**Comment by hesa** [comment]
https://quay.io/

**Comment by hesa** [comment]
https://www.phoronix.com/news/Qt-Wayland-Compositor-Restart

**Comment by hesa** [comment]
https://lwn.net/Articles/924133/

**Comment by hesa** [comment]
Curl turns 25...in case you did not notice

**Comment by hesa** [comment]
Ubuntu not shipping flatpak

**Comment by bagder** [comment]
March ended. Episode is pending.
