### ISSUE TITLE
Where are the women in Open Source?

### ISSUE THREAD

**Issue by oej** [fossified/podcast#32]
https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/where-are-women-open-source

"Study after study has proven that women are underrepresented in virtually all sectors of ICT. Women make up a quarter of all persons working in the tech industry, according to PwC’s [Women in Tech report](https://www.pwc.co.uk/women-in-technology/women-in-tech-report.pdf) (2017). Open source communities are even more male-dominated - women never make up more than 10% of their contributors and participants."

What can we do to make FOSS more inviting and women friendly? Do we understand the problem to fix?

**Comment by oej** [comment]
Like your comment in #33 that we need some guests to balance the group of white grumpy men...

**Comment by e8johan** [comment]
Some input. Two great talks by Patricia. 

https://patricia.no/2019/02/04/keynote_deconstructing_privilege.html
https://patricia.no/2019/09/12/survival_tips_for_women_in_tech.html

The first one establishes that there is such a thing as privilege, the other one perspective of privilege.

**Comment by ghost** [comment]
If you want, I can cast around for potential (female) guests in my network.

**Comment by hesa** [comment]
@svtfrida I am not sure but I think we're seeing more women (than before) in non-hacker/developer/engineering roles but when it comes to the more techie roles (again hacker/developer/engineering) I suspect it is only somewhat better. I do not have any data behind this so I am basing this on my work experience at misc companies and projects. Do you think it makes more/most sense to invite a female techie?

**Comment by ghost** [comment]
@hesa I agreee, this is the development I have seen for the past 10-15 years I think. Maybe it would be good to have women from different roles? The ideal would probably be to talk to someone who has tried and given up, to avoid survivor's bias...but on the other hand many of us have been pretty close to that point on several occasions but still ended up staying in tech (and open source). If I have to choose just one, I would suggest a techie :)

**Comment by bagder** [comment]
I think having two guests for this would be better than one, if nothing else to help make sure that we get more than "just one person's view", and to better counter-balance the (male) hosts.

**Comment by hesa** [comment]
@svtfrida and @bagder, more than one sounds great. 

@svtfrida ... When I started working in IT (late 90s) things were even worse. .... getting better, but too slowly

**Comment by oej** [comment]
It's getting better in the workplace, but very few female engineers stay close to coding, they tend to escalate to project managers or other roles quicker than the rest. And in open source teams, they are still very very rare. What can we do better? Do we need mentorships?

**Comment by yabellini** [comment]
This can be good material for this chat: https://theconversation.com/the-retention-problem-women-are-going-into-tech-but-are-also-being-driven-out-200625

**Comment by yabellini** [comment]
This is another researcher interesting for this topic: What is Open Source for Social Good and Why People Contribute?. Denae Ford. https://blog.denaeford.me/2022/10/25/what-is-open-source-for-social-good-and-why-people-contribute/

**Comment by ghost** [comment]
@yabellini That was a very good summarizing article!

As is the case in many other fields, there is actually tons of data and research about what upholds the current situation. I would personally be more interested to hear / talk about what we can actually change in order to improve the situation, than iterate on the problem description.

**Comment by cybette** [comment]
Found my way here via [this toot](https://camp.smolnet.org/@frida/110026840897025063). Hi @e8johan!

I've been in the industry for 20+ years. Started off as an engineer, experienced the usual harassment/discrimination etc., wasn't moving up the career ladder, wanted to quit the industry but love tech too much. Nowadays doing community management (for open source projects), I think things have been improving but not fast enough.

**Comment by yabellini** [comment]
For sure! But if you don't define the problem well, it is hard to try to find a solution, right? 
And we don't even start talking about intersectionality.  We only focus on the gender dimension here. :-) 

Here is another one that gives some tips in the direction of what we can do (but focus only on one aspect of the problem, the newcomers, not about retention for example): Ten simple rules for helping newcomers become contributors to open projects https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007296

As you can see, I'm citing a lot to Denae Ford, who works at Microsoft on this topic.  Perhaps an interesting potential participant. :-)

**Comment by trallard** [comment]
Oh as a woman in OSS (with many non-men colleagues and friends in OSS, too), I could speak about this for days or weeks. 
The lack of diversity, not only gender, is a multi-layer and truly entrenched systemic issue. 
Factors like reliance on volunteer labour, microaggressions, lack of formal incentives and mentorship programmes to participate in open source, having to prove oneself over and over again, unsafe environments, lack of clear governance and accountability mechanisms, and many others make it extremely hard for individuals from historically marginalised groups to participate (and remain) in open source. 

Additionally, the existing single lane (pathway) from contributor to maintainer also significantly limits the diversity of contributors and the skills they bring. 
We need a multi-disciplinary, radical approach to inclusion (including a cultural and leadership shift) to support, recruit and retain diverse contributors.

**Comment by yabellini** [comment]
> Oh as a women in OSS (with many non-men colleagues and friends in OSS too) I could speak about this for days or weeks. The lack of diversity, not only gender, is a multi layer and truly entrenched systemic issue. Factors like reliance on volunteer labour, micro aggressions, lack of formal incentives and mentorship programmes to participate in open source, having to prove oneself over and over again, unsafe environments, lack of clear governance and accountability mechanisms, and many others, make it extremely hard for individuals from historically marginalised groups to participate (and remain) in open source.
> 
> Additionally, the existing single lane (pathway) from contributor to maintainer also significantly limits the diversity of contributors and skills they bring. We need a multi disciplinary, radical approach to inclusion (including a cultural and leadership shift) to support, recruit and retain a diverse set of contributors.

Hell yes!

**Comment by missmiis** [comment]
I'm pretty well lapsed with my open source contributions, but there was a time... I suspect there are fewer women in open source simply because there are fewer women in tech. I've been doing a lot of reading on this the last couple of years for my own book (itgrrrl.xyz). There's a paper called The Athena Factor that has the most detailed research on the various problems keeping women out of tech that I've seen.

The weirdest thing for me, being an old-timer, is that all the stereotyping happened after I did my degree and started working in the industry. When I was knocking on people's office doors in 1991 and saying "I'm here to put your PC on the network" no one even blinked. But then, no one had knocked on their door and said that before, so why not a 21 year old, punky-haired woman. I think it was definitely harder for women who came later.

**Comment by oej** [comment]
Ok, so the problem seems well defined. Maybe the podcast should focus on "how-tos" - helping projects with the first steps towards a better and more inviting environment and "not-tos" - things that should be avoided.

**Comment by trallard** [comment]
Thanks for your input @missmiis, and I appreciate sharing the context regarding your research into the problem. However, I would like to expand on this:

> I suspect there are fewer women in open source simply because there are fewer women in tech

While having fewer women in tech overall significantly reduces the pool of potential contributors to OSS, attributing this as the primary (or only) factor for the lack of representation in OSS is an oversimplification. It minimises the impact of the many systemic and attitudinal barriers that folks from historically marginalised groups face when trying to participate in OSS.
You are right; many pioneers in tech were women (or not men), which has shifted over time - but this is a consequence of cultural, systemic, and attitudinal shifts.

@oej 

> Maybe the podcast should focus on "how-tos" - helping projects with the first steps towards a better and more inviting environment and "not-tos" - things that should be avoided.

Sure, this would be helpful. Yet while projects can do a lot to make their project more welcoming and inclusive, that alone will not fix the lack of diversity problem. For this to happen, we need an "all hands on deck" approach including all stakeholders (yes, that includes corporations and organisations that benefit from and rely on open source, founders, and the broader tech ecosystem).

Re-reading the other comments here, I fall in the "techie" role but also wear many other hats, and I have seen my fair share of not-men and other groups try and join or join and eventually leave (or be pushed away from) OSS. Again, some reasons folks leave the tech industry or development roles translate to OSS directly, while others are unique to OSS itself. The main reason I have been able to remain in OSS for over 15 years now is that I have a vast deal of privilege and have been lucky enough to have built a strong support network of peers, mentors, and sponsors. I have been close to leaving OSS several times, but ultimately, that network has kept me around long enough.

**Comment by missmiis** [comment]
Absolutely @trallard, there are a lot of complex factors here and I certainly don't have any solutions. Reading up on the history has been interesting from the perspective of understanding a bit more about how we got here, but what to do next? Other than being "visible" as women in tech I don't have much in the way of ideas here.

**Comment by cazfi** [comment]
> 
> While having fewer women in tech overall significantly reduces the pool of potential contributors to OSS,

Not sure how much it's true nowadays, but at least there used to be lot of people who started with minor OSS contributions and ended to tech that way.

**Comment by bagder** [comment]
See #46
